// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4VvGbB7jfhZVqIrg0cOYjOM3U8go9nkw',
    appId: '1:506066913326:web:45a2634c73c0402218f7bf',
    messagingSenderId: '506066913326',
    projectId: 'ulearning-333de',
    authDomain: 'ulearning-333de.firebaseapp.com',
    storageBucket: 'ulearning-333de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUJr53ciSjr2TS_mXhRxcS1s8pfmktZM',
    appId: '1:506066913326:android:75c9e9dfab5f480418f7bf',
    messagingSenderId: '506066913326',
    projectId: 'ulearning-333de',
    storageBucket: 'ulearning-333de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7cKPjbtywYx0w1248LLNEh70_xEh0RQg',
    appId: '1:506066913326:ios:cbc95b99ee56527618f7bf',
    messagingSenderId: '506066913326',
    projectId: 'ulearning-333de',
    storageBucket: 'ulearning-333de.appspot.com',
    iosBundleId: 'com.example.ulearningApp',
  );
}
